### ISSUE TITLE
【Enhancement】日志优化

### ISSUE THREAD

**Issue by tming** [TencentBlueKing/bk-turbo#138]
**What would you like to be added**:
优化server日志（增加或者完善）

**Why is this needed**:
方便维护

**Comment by tming** [comment]
访问mesos接口的地方，加下耗时比较长的日志记录

**Comment by dazuo168** [comment]
在修改info.Status之前的日志中，记录下修改前的info.Status取值
----------
		// In case of info.Status is terminated but some taskgroups are not terminated,
		// then change info.Status to Staging.
		if taskGroup.Status != commonTypes.PodRunning {
			if (info.Status != op.ServiceStatusStaging) &&
				(taskGroup.Status == commonTypes.PodStaging || taskGroup.Status == commonTypes.PodStarting) {

				blog.Warnf(
					"crm: there is still a taskgroup(%s) in status(%s), "+
						"server status will be set to staging by force", taskGroup.Name, taskGroup.Status)
				info.Status = op.ServiceStatusStaging
			}
			continue
		}
